# Generated by Django 4.2 on 2023-12-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_product_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
