# Generated by Django 4.2 on 2023-12-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_alter_product_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Order',
        ),
    ]
