# Generated by Django 4.2 on 2024-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0008_post_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
