# Generated by Django 4.2 on 2024-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0018_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
